import js from '@eslint/js'
import reactHooks from 'eslint-plugin-react-hooks'
import storybook from 'eslint-plugin-storybook'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import { defineConfig, globalIgnores } from 'eslint/config'

/**
 * One config for the whole workspace.
 *
 * haus had a root `lint` script that ran `pnpm -r run lint` while no package
 * defined a `lint` script. It errored and exited 0, so it reported success
 * while linting nothing. This replaces it with a real config; each package's
 * `lint` script now points back here.
 *
 * The environment differs per package, so globals are scoped rather than
 * declared once: the probe's extraction half is authored against the browser
 * even though the package is consumed from Node, and the build scripts are the
 * other way round.
 */
export default defineConfig([
  globalIgnores([
    '**/dist',
    '**/storybook-static',
    '**/node_modules',
    // Generated by the token build; linting output is noise.
    'packages/tokens/src/*.css',
    // The v8 HTML reporter's own scripts. Already gitignored and already out
    // of stylelint's scope; without this they produced 30 of the workspace's
    // warnings, all of them about someone else's code.
    '**/coverage',
  ]),

  {
    files: ['**/*.{ts,tsx}'],
    extends: [js.configs.recommended, tseslint.configs.recommended],
    languageOptions: {
      globals: globals.browser,
    },
    rules: {
      // The underscore prefix is the established signal for a deliberately
      // unused binding: a discarded destructure, or a signature-only parameter.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },

  {
    files: ['packages/components/**/*.tsx'],
    extends: [reactHooks.configs.flat.recommended],
  },

  {
    // Vitest globals are enabled in each package's vitest config, so the test
    // files legitimately reference describe/it/expect without importing them.
    files: ['**/*.test.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node, ...globals.vitest },
    },
  },

  {
    // Build scripts and configs run in Node.
    files: ['**/*.config.{ts,js,mjs}', '**/scripts/**/*.{ts,js,mjs}', '**/.storybook/**/*.{ts,tsx}'],
    languageOptions: {
      globals: globals.node,
    },
  },

  {
    files: ['apps/storybook/**/*.{ts,tsx}'],
    extends: [storybook.configs['flat/recommended']],
  },

  {
    // Stories are documentation. Their render functions use hooks to drive
    // interactive examples, which is not a component boundary the
    // rules-of-hooks lint can recognise.
    files: ['**/*.stories.tsx'],
    rules: {
      'react-hooks/rules-of-hooks': 'off',
    },
  },
])
